---

dist: "xenial"
language: "minimal"

service:
  - "docker"

install:
  - "make docker-build-all -j 2"

script:
  - "make lint-all"

deploy:
  provider: "script"
  script:
    - "echo \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_USERNAME\" --password-stdin"
    - "make docker-push-all"
  on: # yamllint disable rule:truthy
    tags: true

...
