---

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable:
    - "funlen"
    - "lll"
    - "prealloc"
    - "wsl"
  enable-all: true

linters-settings:
  dupl:
    threshold: 100
  errcheck:
    check-type-assertions: true
  gocyclo:
    min-complexity: 13
  gomnd:
    settings:
      mnd:
        checks: "case,return"
  govet:
    use-installed-packages: true
  maligned:
    suggest-new: true
  misspell:
    locale: "US"
  unparam:
    check-exported: true
  whitespace:
    multi-if: true
    multi-func: true

...
